using Cnblogs.DashScope.Core.Internals;

namespace Cnblogs.DashScope.Core;

/// <summary>
/// Represents a chat message between the user and the model.
/// </summary>
/// <param name="Role">The role of this message.</param>
/// <param name="Content">The content of this message.</param>
/// <param name="Name">Used when role is tool, represents the function name of this message generated by.</param>
/// <param name="ToolCalls">Calls to the function.</param>
public record ChatMessage(string Role, string Content, string? Name = null, List<ToolCall>? ToolCalls = null) : IMessage<string>;
